services:
  - type: web
    name: spotify-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: NODE_VERSION
        value: 20
